frequency: 20
sensor_timeout: 0.5
two_d_mode: true  
transform_time_offset: 0.0
transform_timeout: 0.0
print_diagnostics: true

odom0: /wheel_odom
# odom0_config: [true,  true,  false,  
#                true, true, false,   
#                true, false, false,  
#                false, false, true,
#                false, false, false]  
#correct
odom0_config: [true, true,  false,  
               false, false, false,   
               true, true, true,  
               false, false, true,
               false, false, false]    
odom0_queue_size: 10
odom0_nodelay: true
odom0_differential: false
odom0_relative: false

imu0: /imu/data
# imu0_config: [false, false, false,   # x, y, z 位置
#               false, false, false,    # x, y, z 速度
#               true,  true,  true,   # 滾動, 俯仰, 偏航 位置
#               true, true, true]    # 滾動, 俯仰, 偏航 速度
imu0_config: [false, false, false,   # x, y, z 位置
              true, true, false,    # x, y, z 速度
              false,  false,  false,   # 滾動, 俯仰, 偏航 位置
              true, true, true,
              true, true, true]    # 滾動, 俯仰, 偏航 速度
imu0_queue_size: 10
imu0_nodelay: true
imu0_differential: true
imu0_relative: true

use_control: false
stamped_control: false

# wheel_odom
world_frame: odom
map_frame: map
# wheel_odom
odom_frame: odom
base_link_frame: base_footprint
